# @package _global_
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

band_rotation:
  _target_: emg2qwerty.transforms.ForEach  # i.i.d rotation offset for each band
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets: [-1, 0, 1]

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120  # Max 60ms jitter for 2kHz EMG

resample:
  _target_: emg2qwerty.transforms.Resample
  orig_freq: 2000 # 2000 Hz
  new_freq: 1000 # 1000 Hz

# if used, be sure to update ELECTRODE_CHANNELS in lightning.py and
# in_features in tds_conv_ctc.yaml
drop_channels:
  _target_: emg2qwerty.transforms.DropChannels
  drop_channels: [0, 7, 10, 15]

mask_channels:
  _target_: emg2qwerty.transforms.ChannelMask
  mask_channels: [15]

logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 20  # Downsamples from 2kHz to 100Hz

specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25  # Max 200ms per time mask for 125Hz spectrogram
  n_freq_masks: 2
  freq_mask_param: 4

transforms:
  train:
    - ${to_tensor}
    - ${drop_channels}
    - ${band_rotation}
    - ${temporal_jitter}
    # - ${resample}
    - ${logspec}
    - ${specaug}

  val:
    - ${to_tensor}
    # - ${resample}
    - ${drop_channels}
    # - ${mask_channels}
    - ${logspec}

  test: ${transforms.val}
